name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  branch-name: ${GITHUB_REF#refs/heads/}

jobs:
  scalafmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sbt scalafmtCheck

  buildSbt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sbt -J-Xmx2G test
